language: generic
sudo: false
addons:
  apt:
    packages:
    - zlib1g-dev
    - libgdbm-dev
env:
  - GAUCHE_VERSION=0.9.4
  - GAUCHE_VERSION=0.9.5
  - GAUCHE_VERSION=0.9.6
before_install:
  - curl -s -o get-gauche.sh https://raw.githubusercontent.com/shirok/get-gauche/master/get-gauche.sh
  - chmod u+x get-gauche.sh
  - ./get-gauche.sh --auto --home --version "$GAUCHE_VERSION"
script:
  - gosh -V
  - ./configure
  - make check
